spring.application.name=InvoiceHub
server.port=8085

server.address=0.0.0.0

# Forward headers strategy (for reverse proxy)
server.forward-headers-strategy=native

# MongoDB connection URI
#spring.mongodb.uri=mongodb://localhost:27017/app-jokati--local
spring.mongodb.uri=mongodb://admin:strongpassword@82.165.160.231:27017/app-jokati--local?authSource=admin


# Optional: Connection pool settings
spring.data.mongodb.auto-index-creation=true


# Global log level
logging.level.root=INFO

# Set log level for a specific package
logging.level.com.jokati.invoice=DEBUG


# ========= Console Formatting =========
# Customize console log pattern (date, level, logger, thread, message)
logging.pattern.console=%d{ISO8601} [%thread] [%X{traceId}] [%X{application}] %-5level %logger{36} - %msg%n

# ========= File Output =========
# Single file output (no rolling). For rolling, use logback-spring.xml (see note below)
logging.file.name=logs/jokati-app.log

# Customize file log pattern
logging.pattern.file=%d{ISO8601} [%thread] [%X{traceId}] [%X{application}] %-5level %logger{36} - %msg%n

# ========= Color (console) =========
# Enabled by default on supported terminals; force enable/disable as needed
# spring.output.ansi.enabled=ALWAYS

# ========= Actuator (optional for dynamic log level) =========
# Expose loggers endpoint to change levels at runtime
management.endpoints.web.exposure.include=loggers,health,info
management.endpoint.loggers.enabled=true
management.endpoint.health.show-details=always

# Metrics distribution
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# in dev environment and false in production
springdoc.swagger-ui.enabled=true


# application.properties
spring.mail.host=smtp.ionos.de
spring.mail.port=587
spring.mail.username=info@jokati.app
spring.mail.password=P$1BwFQlpXKPJd0RAytoj

# Use STARTTLS (explicit TLS)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8

# Default FROM address (optional; used by EmailService if present)
spring.mail.from=info@jokati.app


