
package com.jokati.invoice.mapper;

import com.jokati.invoice.dto.ShipmentItemRequestDTO;
import com.jokati.invoice.dto.ShipmentItemResponseDTO;
import com.jokati.invoice.model.ShipmentItemDocument;

public final class ShipmentMapper {

    private ShipmentMapper() {}

    // Request (PascalCase) -> Document (mirror Id & id)
    public static ShipmentItemDocument toDocument(ShipmentItemRequestDTO r) {
        return ShipmentItemDocument.builder()
                .idUpper(r.getIdUpper())
                .idLower(r.getIdLower())
                .shipmentId(r.getShipmentId())          // keep newline if present
                .shipmentDate(r.getShipmentDate())      // keep as sent
                .zipCodeShipper(r.getZipCodeShipper())
                .zipCodeConsignee(r.getZipCodeConsignee())
                .city(r.getCity())
                .country(r.getCountry())
                .length(r.getLength())
                .wide(r.getWide())
                .height(r.getHeight())
                .loadingMeters(r.getLoadingMeters())
                .cubicMeters(r.getCubicMeters())
                .palletCount(r.getPalletCount())
                .packagingType(r.getPackagingType())
                .effectiveWeight(r.getEffectiveWeight())
                .chargeableWeight(r.getChargeableWeight())
                .minimumWeight(r.getMinimumWeight())
                .weightByCubicMeters(r.getWeightByCubicMeters())
                .weightByLoadingMeters(r.getWeightByLoadingMeters())
                .stackable(r.getStackable())
                .stackFactor(r.getStackFactor())
                .stackId(r.getStackId())
                .stackFootprintLoadingMeters(r.getStackFootprintLoadingMeters())
                .expressNextDay(r.getExpressNextDay())
                .express12(r.getExpress12())
                .express10(r.getExpress10())
                .express8(r.getExpress8())
                .fixtermin(r.getFixtermin())
                .emailAvis(r.getEmailAvis())
                .phoneAvis(r.getPhoneAvis())
                .bookingInAvis(r.getBookingInAvis())
                .dangerousGoodsSurcharge(r.getDangerousGoodsSurcharge())
                .longGoodsSurcharge(r.getLongGoodsSurcharge())
                .shortWeekSurcharge(r.getShortWeekSurcharge())
                .palletExchange(r.getPalletExchange())
                .palletBoxExchange(r.getPalletBoxExchange())
                .carrierCertificate(r.getCarrierCertificate())
                .b2cNationalSurcharge(r.getB2cNationalSurcharge())
                .b2cInternationalSurcharge(r.getB2cInternationalSurcharge())
                .securityFee(r.getSecurityFee())
                .insurance(r.getInsurance())
                .portiPapiere(r.getPortiPapiere())
                .custom1(r.getCustom1())
                .custom2(r.getCustom2())
                .custom3(r.getCustom3())
                .custom4(r.getCustom4())
                .custom5(r.getCustom5())
                .message(r.getMessage())
                .errorType(r.getErrorType())
                .price(r.getPrice())
                .totalPrice(r.getTotalPrice())
                .extraCostsTotalPrice(r.getExtraCostsTotalPrice())
                .toll(r.getToll())
                .tollPercent(r.getTollPercent())
                .diesel(r.getDiesel())
                .dieselPercent(r.getDieselPercent())
                .isConsolidated(r.getIsConsolidated())
                .isConsolidatedSum(r.getIsConsolidatedSum())
                .hasPackagingType(r.getHasPackagingType())
                .projectType(r.getProjectType())
                .undefined(r.getUndefined())
                .build();
    }

    // Document -> Response (PascalCase); ensure both Id & id present
    public static ShipmentItemResponseDTO toResponse(ShipmentItemDocument s) {
        String idUpper = s.getIdUpper() != null ? s.getIdUpper() : s.getIdLower();
        String idLower = s.getIdLower() != null ? s.getIdLower() : s.getIdUpper();

        return ShipmentItemResponseDTO.builder()
                .idUpper(idUpper)
                .idLower(idLower)
                .shipmentId(s.getShipmentId())
                .shipmentDate(s.getShipmentDate())
                .zipCodeShipper(s.getZipCodeShipper())
                .zipCodeConsignee(s.getZipCodeConsignee())
                .city(s.getCity())
                .country(s.getCountry())
                .length(s.getLength())
                .wide(s.getWide())
                .height(s.getHeight())
                .loadingMeters(s.getLoadingMeters())
                .cubicMeters(s.getCubicMeters())
                .palletCount(s.getPalletCount())
                .packagingType(s.getPackagingType())
                .effectiveWeight(s.getEffectiveWeight())
                .chargeableWeight(s.getChargeableWeight())
                .minimumWeight(s.getMinimumWeight())
                .weightByCubicMeters(s.getWeightByCubicMeters())
                .weightByLoadingMeters(s.getWeightByLoadingMeters())
                .stackable(s.getStackable())
                .stackFactor(s.getStackFactor())
                .stackId(s.getStackId())
                .stackFootprintLoadingMeters(s.getStackFootprintLoadingMeters())
                .expressNextDay(s.getExpressNextDay())
                .express12(s.getExpress12())
                .express10(s.getExpress10())
                .express8(s.getExpress8())
                .fixtermin(s.getFixtermin())
                .emailAvis(s.getEmailAvis())
                .phoneAvis(s.getPhoneAvis())
                .bookingInAvis(s.getBookingInAvis())
                .dangerousGoodsSurcharge(s.getDangerousGoodsSurcharge())
                .longGoodsSurcharge(s.getLongGoodsSurcharge())
                .shortWeekSurcharge(s.getShortWeekSurcharge())
                .palletExchange(s.getPalletExchange())
                .palletBoxExchange(s.getPalletBoxExchange())
                .carrierCertificate(s.getCarrierCertificate())
                .b2cNationalSurcharge(s.getB2cNationalSurcharge())
                .b2cInternationalSurcharge(s.getB2cInternationalSurcharge())
                .securityFee(s.getSecurityFee())
                .insurance(s.getInsurance())
                .portiPapiere(s.getPortiPapiere())
                .custom1(s.getCustom1())
                .custom2(s.getCustom2())
                .custom3(s.getCustom3())
                .custom4(s.getCustom4())
                .custom5(s.getCustom5())
                .message(s.getMessage())
                .errorType(s.getErrorType())
                .price(s.getPrice())
                .totalPrice(s.getTotalPrice())
                .extraCostsTotalPrice(s.getExtraCostsTotalPrice())
                .toll(s.getToll())
                .tollPercent(s.getTollPercent())
                .diesel(s.getDiesel())
                .dieselPercent(s.getDieselPercent())
                .isConsolidated(s.getIsConsolidated())
                .isConsolidatedSum(s.getIsConsolidatedSum())
                .hasPackagingType(s.getHasPackagingType())
                .projectType(s.getProjectType())
                .undefined(s.getUndefined())
                .build();
    }
}
